In [21]:
ofrom sklearn import datasets 
digits = datasets.load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [22]:
print(digits.images[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [24]:
import matplotlib.pyplot as plt
 
def plot_multi(i):
    nplots = 16
    fig = plt.figure(figsize=(15, 15))
    for j in range(nplots):
        plt.subplot(4, 4, j+1)
        plt.imshow(digits.images[i+j], cmap='binary')
        plt.title(digits.target[i+j])
        plt.axis('off')
   
    plt.show()
 
    plot_multi(0)

In [7]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [8]:

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X.shape[1],)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [9]:

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [10]:

model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/20


45/45 [==============================] - 2s 14ms/step - loss: 1.9345 - accuracy: 0.4579 - val_loss: 1.5171 - val_accuracy: 0.8389
Epoch 2/20
45/45 [==============================] - 0s 7ms/step - loss: 1.2531 - accuracy: 0.7912 - val_loss: 0.9190 - val_accuracy: 0.8750
Epoch 3/20
45/45 [==============================] - 0s 6ms/step - loss: 0.8018 - accuracy: 0.8636 - val_loss: 0.5898 - val_accuracy: 0.8944
Epoch 4/20
45/45 [==============================] - 0s 7ms/step - loss: 0.5542 - accuracy: 0.9005 - val_loss: 0.4192 - val_accuracy: 0.9167
Epoch 5/20
45/45 [==============================] - 0s 7ms/step - loss: 0.4306 - accuracy: 0.9054 - val_loss: 0.3335 - val_accuracy: 0.9306
Epoch 6/20
45/45 [==============================] - 0s 7ms/step - loss: 0.3547 - accuracy: 0.9283 - val_loss: 0.2782 - val_accuracy: 0.9389
Epoch 7/20
45/45 [==============================] - 0s 6ms/step - loss: 0.3001 - accuracy: 0.9381 - val_loss: 0.2462 - val_accuracy: 0.9389
Epoch 8/20
45/45 

In [11]:

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {accuracy * 100:.2f}%")


12/12 [==============================] - 0s 3ms/step - loss: 0.1090 - accuracy: 0.9750
Test accuracy: 97.50%
